FROM            python:3.6.4-slim
MAINTAINER      rainsound128@gmail.com

# nginx, supervisor 설치
RUN             apt-get -y update
RUN             apt-get -y dist-upgrade
RUN             apt-get -y install build-essential nginx supervisor

# requirements 폴더 복사
COPY            .requirements /srv/.requirements

WORKDIR         /srv
RUN             pip install -r /srv/.requirements/production.txt
