# Generated by Django 2.0.5 on 2018-05-15 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('f', '여성')], default=django.utils.timezone.now, max_length=1, verbose_name='성별'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='generation',
            field=models.CharField(choices=[('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대 이상')], default=django.utils.timezone.now, max_length=1, verbose_name='세대'),
            preserve_default=False,
        ),
    ]
