# Generated by Django 2.0.5 on 2018-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180515_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('f', '여성')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.CharField(choices=[('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대 이상')], max_length=10, verbose_name='세대'),
        ),
    ]
