# Generated by Django 2.0.5 on 2018-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180524_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
        ),
    ]
