# Generated by Django 2.0.5 on 2018-06-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('purchase_url', models.URLField(blank=True, max_length=400, verbose_name='상품 URL')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('category', models.CharField(choices=[('a', '패션의류/잡화'), ('b', '유아용품'), ('c', '뷰티'), ('d', '주방/생활용품'), ('e', '디지털/가전제품'), ('f', '가구/인테리어'), ('g', '운동용품'), ('h', '여행'), ('i', '도서/음반/공연'), ('j', '자동차용품'), ('k', '기타')], max_length=100, verbose_name='상품 카테고리')),
                ('img', models.ImageField(blank=True, upload_to='items', verbose_name='상품 이미지')),
                ('public_visibility', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('is_purchase', models.BooleanField(default=False, verbose_name='구매 여부')),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_info_list', to='items.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
