# Generated by Django 2.0.5 on 2018-05-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('purchase_url', models.CharField(blank=True, max_length=200, verbose_name='상품 URL')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='상품 카테고리')),
                ('img_url', models.ImageField(blank=True, upload_to='items', verbose_name='상품 이미지')),
                ('public_visibility', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_info_list', to='items.Item')),
            ],
        ),
    ]
