# Generated by Django 2.0.5 on 2018-05-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180517_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_url',
            field=models.URLField(blank=True, verbose_name='상품 URL'),
        ),
    ]
