# Generated by Django 2.0.5 on 2018-05-21 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_purchase',
            field=models.BooleanField(default=False, verbose_name='구매 여부'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
    ]
