# Generated by Django 2.0.5 on 2018-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180521_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
