# Generated by Django 2.0.5 on 2018-05-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180521_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='itemcomment',
            options={'ordering': ['created_time']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='itemcomment',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='itemlike',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='item',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemlike',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
