# Generated by Django 2.0.5 on 2018-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180524_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('a', '패션의류/잡화'), ('b', '유아용품'), ('c', '뷰티'), ('d', '주방/생활용품'), ('e', '디지털/가전제품'), ('f', '가구/인테리어'), ('g', '운동용품'), ('h', '여행'), ('i', '도서/음반/공연'), ('j', '자동차용품'), ('k', '기타')], max_length=100, verbose_name='상품 카테고리'),
        ),
    ]
