# Generated by Django 2.0.5 on 2018-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20180530_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=400, verbose_name='상품 URL'),
        ),
    ]
